sudo: required
services:
    - docker

before_install:
    - docker build -t docker-complex-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true docker-complex-test npm test

after_success:
    - docker build -t ctobyn/multi-client ./client
    - docker build -t ctobyn/multi-nginx ./nginx
    - docker build -t ctobyn/multi-server ./server
    - docker build -t ctobyn/multi-worker ./worker

    - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push ctobyn/multi-client
    - docker push ctobyn/multi-nginx
    - docker push ctobyn/multi-server
    - docker push ctobyn/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-615499284044
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY